name: shareed_todo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  google_sign_in: ^6.3.0
  provider: ^6.1.4
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplayBlackItalic.otf
        - asset: assets/fonts/SFProDisplayLightItalic.otf
        - asset: assets/fonts/SFProDisplaySemiBoldItalic.otf
        - asset: assets/fonts/SFProDisplayBold.otf
        - asset: assets/fonts/SFProDisplayMedium.otf
        - asset: assets/fonts/SFProDisplayThinItalic.otf
        - asset: assets/fonts/SFProDisplayHeavyItalic.otf
        - asset: assets/fonts/SFProDisplayRegular.otf
        - asset: assets/fonts/SFProDisplayUltraLightItalic.otf
